### ISSUE TITLE
eval problem

### ISSUE THREAD

**Issue by YINNNM** [SherlockHolmes221/DOQ#13]
```
(pytorch) user_ym@cs_3090:~/code/DOQ$ python generate_vcoco_official.py --param_path outputs/vcoco/ts_model/checkpoint.pth --save_path vcoco.pickle --hoi_path ~/code/dataset/vcoco --model_name hoi_ts_qpos_eobj_kl
git:
  sha: de1bc1397e6e94a5449cb16101b1f93ae7220eb5, status: has uncommited changes, branch: main

Namespace(backbone='resnet50', batch_size=2, dataset_file='vcoco', dec_layers=6, device='cuda', dilation=False, dim_feedforward=2048, dropout=0.1, enc_layers=6, hidden_dim=256, hoi_path='/home/user_ym/code/dataset/vcoco', missing_category_id=80, model_name='hoi_ts_qpos_eobj_kl', nheads=8, num_obj_classes=80, num_queries=100, num_verb_classes=117, num_verb_queries=100, num_workers=2, param_path='outputs/vcoco/ts_model/checkpoint.pth', position_embedding='sine', pre_norm=False, save_path='vcoco.pickle', subject_category_id=0)
Traceback (most recent call last):
  File "generate_vcoco_official.py", line 579, in <module>
    main(args)
  File "generate_vcoco_official.py", line 488, in main
    num_verb_classes=args.num_verb_classes)
TypeError: build_hoi_ts() got an unexpected keyword argument 'begin_l'
```

May I ask if you have had this problem? How do I fix it?

**Comment by YINNNM** [comment]
I added some parameters to the parser, but a new problem appeared
Here are the parameters I added
```
    # * HOI补充
    parser.add_argument('--num_obj_classes', type=int, default=80,
                        help="Number of object classes")
    parser.add_argument('--num_verb_classes', type=int, default=117,
                        help="Number of verb classes")
    parser.add_argument('--no_aux_loss', dest='aux_loss', action='store_false',
                        help="Disables auxiliary decoding losses (loss at each layer)")
```

The new problem is
```
Namespace(aux_loss=True, backbone='resnet50', batch_size=2, dataset_file='vcoco', dec_layers=6, device='cuda', dilation=False, dim_feedforward=2048, dropout=0.1, enc_layers=6, hidden_dim=256, hoi_path='/home/user_ym/code/dataset/vcoco', missing_category_id=80, model_name='hoi_ts_qpos_eobj_kl', nheads=8, num_obj_classes=80, num_queries=100, num_verb_classes=117, num_verb_queries=100, num_workers=2, param_path='outputs/vcoco/ts_model/checkpoint.pth', position_embedding='sine', pre_norm=False, save_path='vcoco.pickle', subject_category_id=0)
Traceback (most recent call last):
  File "generate_vcoco_official.py", line 579, in <module>
    main(args)
  File "generate_vcoco_official.py", line 506, in main
    model.load_state_dict(checkpoint['model'])
  File "/home/user_ym/miniconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DETRHOI:
        size mismatch for obj_class_embed.weight: copying a param with shape torch.Size([82, 256]) from checkpoint, the shape in current model is torch.Size([81, 256]).
        size mismatch for obj_class_embed.bias: copying a param with shape torch.Size([82]) from checkpoint, the shape in current model is torch.Size([81]).
        size mismatch for verb_class_embed.weight: copying a param with shape torch.Size([29, 256]) from checkpoint, the shape in current model is torch.Size([117, 256]).
        size mismatch for verb_class_embed.bias: copying a param with shape torch.Size([29]) from checkpoint, the shape in current model is torch.Size([117]).
```
