### ISSUE TITLE
Exception: not support dateset

### ISSUE THREAD

**Issue by xz-123-new** [SherlockHolmes221/DOQ#3]
I tried to train the model on hicodet dataset, but there was a problem, and the error message was as follows:
Traceback (most recent call last):
  File "/home/xuzhu/DOQ/main.py", line 322, in <module>
    main(args)
  File "/home/xuzhu/DOQ/main.py", line 267, in main
    train_stats = train_one_epoch(
  File "/home/xuzhu/DOQ/engine.py", line 43, in train_one_epoch
    for samples, targets in metric_logger.log_every(data_loader, print_freq, header):
  File "/home/xuzhu/DOQ/util/misc.py", line 228, in log_every
    for obj in iterable:
  File "/home/xuzhu/anaconda3/envs/qpic/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/xuzhu/anaconda3/envs/qpic/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1065, in _next_data
    return self._process_data(data)
  File "/home/xuzhu/anaconda3/envs/qpic/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/xuzhu/anaconda3/envs/qpic/lib/python3.9/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
Exception: Caught Exception in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/xuzhu/anaconda3/envs/qpic/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/xuzhu/anaconda3/envs/qpic/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xuzhu/anaconda3/envs/qpic/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xuzhu/DOQ/datasets/hico.py", line 65, in __getitem__
    img_anno, img = get_replace_image(random_index, self.annotations, self.img_folder, "hoia")
  File "/home/xuzhu/DOQ/datasets/stitch_images.py", line 462, in get_replace_image
    raise Exception('not support dateset')
Exception: not support dateset

But when I change the code ‘img_anno, img = get_replace_image(random_index, self.annotations, self.img_folder, "hoia")’ into 'img_anno, img = get_replace_image(random_index, self.annotations, self.img_folder, "hico")',i.e. change dataset_file from hoia to hico,it could train as normal,i'm not sure if i was doing the correct thing,could you please explain it to me.Looking foward to your reply,thanks!

**Comment by SherlockHolmes221** [comment]
it is  correct, will fix it soon
